perf: allow @torch.compile by avoiding in-place operation for MaskedConv
`@torch.compile` can speed up model training by 5% - 200%. Simply use:

```python
model = torch.compile(model)
```

This commit resolves the error that comes up when compiling MaskedConv2d:

```none
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.
```